### ISSUE TITLE
Add the navigation bar

### ISSUE THREAD

**Issue by RealBizNoel1985** [nss-evening-cohort-26/gitsub-incognito-mode#20]
**User Story**

The nav bar needs to be accessible for all the required pages for the Github clone.   The user will enter info regarding current and past repositories

**Acceptance Criteria**
The navigation bar needs to use bootstrap and have the 

**Dependecies**
Dependencies will need to be verified  with proper HTML, CSS 

**Dev Notes**
Make sure we have HTML, CSS

**Comment by vtaylordavis** [comment]
Navbar added and functional!
